services:
    postgre:
        image: postgres:${POSTGRES_TAG:-12.17}
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-minhasenha}
            POSTGRES_USER: ${POSTGRES_USER:-gps}
            POSTGRES_DB: ${POSTGRES_DB:-kubenews}
        volumes: 
            -  postgre_docker_vol:/var/lib/postgresql/data
        networks:
            - kube_news_net

    kube_news:
        image: gersonporciuncula/kube-news:${KUBE_NEWS_TAG:-latest}
        build: 
            context: ./src
            dockerfile: Dockerfile

        ports:
            - 8080:8080   
        networks:
            - kube_news_net
        depends_on:
            - postgre
        environment:
            DB_PASSWORD: ${POSTGRES_PASSWORD:-minhasenha}
            DB_USERNAME: ${POSTGRES_USER:-gps}
            DB_DATABASE: ${POSTGRES_DB:-kubenews} 
            DB_HOST: postgre

volumes:
    postgre_docker_vol:
        
networks:
    kube_news_net:
        name: kbnetwork
        driver: bridge